# Generated by Django 4.0.4 on 2022-05-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecutionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=100)),
                ('execution_id', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=2)),
                ('code', models.TextField(default='null')),
                ('code_test', models.TextField(default='null')),
                ('code_result', models.IntegerField()),
                ('result', models.CharField(max_length=1000)),
            ],
        ),
    ]
