# Generated by Django 4.0.4 on 2022-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExecutionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.IntegerField(unique=True)),
                ('language', models.CharField(default='py', max_length=2)),
                ('code', models.TextField(blank=True, null=True)),
                ('code_result', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
