# Generated by Django 4.0.4 on 2022-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeexecutionresponse',
            name='language',
            field=models.CharField(default='no', max_length=2),
        ),
    ]
